### ISSUE TITLE
Can't open Hippo behind a proxy

### ISSUE THREAD

**Issue by Israphel** [Vytax/hippo#1]
Compilation went ok.

tabris@cfadon:~/Development/hippo$ ./hippo 
createRequest() "qrc:///html/noteajax.html" 
init() 
createRequest() "qrc:///html/style.css" 
createRequest() "qrc:///html/prototype.js" 
createRequest() "qrc:///html/pdfbrowser.js" 
createRequest() "qrc:///html/editor.js" 
JS:  "setup()" 
NETWORK ERROR: 4 "Socket operation timed out" 
NET ERROR 

OS: Xubuntu 14.04.1 x64, libqt4, libpoppler, libhunspell.

**Comment by Vytax** [comment]
Proxy support isn't yet implemented. I will add this feature in near feature. 
Thanks.

**Comment by Vytax** [comment]
I have just done a proxy compatibility. Hippo Notes should work with the proxies, which has ports 443 and 80 opened.

**Comment by Israphel** [comment]
Works ok, thanks!
