### ISSUE TITLE
Hoppo-notes re-login

### ISSUE THREAD

**Issue by jackfido** [Vytax/hippo#10]
Hippo notes request login every time is started... I suppose it should work with login saved, right? and once time Im into it show me is sync, but it does not have any notes sinc

**Comment by Vytax** [comment]
Which distro are you using? I think, it have some problem with sqlite.

**Comment by jackfido** [comment]
Im using ubuntu 14.10 64 bits, i have installed sqlite browser, it can help me?

**Comment by Vytax** [comment]
I have tested with Ubuntu 14.04 32bit. It works without any problems. 

Maybe libqt5sql5-sqlite is not installed?  
Also you can find a log file called hippo.log in the folder: /home/[user]/.local/share/HippoNotes/hippo/ In this file you can get more details about this problem.

**Comment by jackfido** [comment]
I have the library installed

Is normal to see the /home/[user]/.local/share/HippoNotes folder as locked?

this is mi log...

2015-03-22T03:15:57.938 [Info   ] <main> Starting the application
2015-03-22T03:16:03.330 [Debug  ] EdamProtocol::init init()
2015-03-22T03:16:03.691 [Info   ] oauth::oauth Authentificate started
2015-03-22T03:16:04.810 [Info   ] jsBridge::debug setup()
2015-03-22T03:16:04.811 [Debug  ] NetDownloadState::request NetDownloadState::request()
![screenshot from 2015-04-20 22 00 56](https://cloud.githubusercontent.com/assets/5467389/7244929/befb6ee2-e7a8-11e4-9339-4e2e298d5174.png)
