### ISSUE TITLE
Makefile:1023: recipe for target 'tmp/speller.o' failed

### ISSUE THREAD

**Issue by jackfido** [Vytax/hippo#2]
Im new on QT compilations, Im using Ubuntu 14.10 64 bits, i have the next error:

at the final of terminal log...
 #include <hunspell/hunspell.hxx>
                                 ^
compilation terminated.
Makefile:1023: recipe for target 'tmp/speller.o' failed
make: **\* [tmp/speller.o] Error 1

some one know if i forget some library or if it is another problem?

**Comment by Vytax** [comment]
Do you have "libhunspell-dev" and "libhunspell-1.3-0" installed?

**Comment by jackfido** [comment]
I have not installed the "libhunspell-dev" library, but i already install... I dont know if we can keep in this topic but now I receive other error:

jackfido@jackfido:~/Downloads/hippo-master$ make
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DQT_STATICPLUGIN -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBKIT_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_CONCURRENT_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -isystem /usr/include/poppler/qt5 -I3rdparty/qtsingleapplication -I3rdparty/zlib -I3rdparty/rc2 -I3rdparty/QFreeDesktopMime -I3rdparty/qblowfish -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebKitWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebKit -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Itmp -Itmp -o tmp/speller.o 3rdparty/spellcheck/speller.cpp
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DQT_STATICPLUGIN -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBKIT_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_CONCURRENT_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -isystem /usr/include/poppler/qt5 -I3rdparty/qtsingleapplication -I3rdparty/zlib -I3rdparty/rc2 -I3rdparty/QFreeDesktopMime -I3rdparty/qblowfish -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebKitWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebKit -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Itmp -Itmp -o tmp/qtwebkitplugin.o 3rdparty/spellcheck/qtwebkitplugin.cpp
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DQT_STATICPLUGIN -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBKIT_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_CONCURRENT_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -isystem /usr/include/poppler/qt5 -I3rdparty/qtsingleapplication -I3rdparty/zlib -I3rdparty/rc2 -I3rdparty/QFreeDesktopMime -I3rdparty/qblowfish -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebKitWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebKit -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Itmp -Itmp -o tmp/main.o main.cpp
In file included from customnetworkaccessmanager.h:4:0,
                 from edamprotocol.h:9,
                 from mainwindow.h:11,
                 from main.cpp:4:
pdfcache.h:8:25: fatal error: poppler-qt5.h: No such file or directory
 #include <poppler-qt5.h>
                         ^
compilation terminated.
Makefile:1048: recipe for target 'tmp/main.o' failed
make: **\* [tmp/main.o] Error 1

**Comment by Vytax** [comment]
You need „libpoppler-qt5-dev“ or similar package.

**Comment by jackfido** [comment]
Nice ! thnx a lot!

Now it is functional and pretty :)
