### ISSUE TITLE
Sort notes by modified ascending/descending

### ISSUE THREAD

**Issue by FuturePilot** [Vytax/hippo#6]
Currently sorting notes by date modified only goes ascending. It would be nice to be able to sort in descending order.

**Comment by Vytax** [comment]
Ok. I will add this feature, when i have some time.

**Comment by FuturePilot** [comment]
Cool. Thanks!

**Comment by Vytax** [comment]
I have added this feature in last commit.

**Comment by FuturePilot** [comment]
Thank you!
